version: '3.8'
services:
  node:
    image: node:17
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # workaround for https://github.com/webpack/webpack/issues/14532
